name: just_audio_example
description: Demonstrates how to use the just_audio plugin.
publish_to: 'none'
version: 4.0.0+1

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_session: ^0.1.14
  rxdart: ^0.27.2
  just_audio:
    path: ../../just_audio
  just_audio_background:
    path: ..
  google_mobile_ads: ^3.0.0

# Uncomment when testing platform interface changes.
# dependency_overrides:
#   just_audio_platform_interface:
#     path: ../../just_audio_platform_interface
#   just_audio_web:
#     path: ../../just_audio_web

dev_dependencies:
  # TODO: uncomment these dependencies when they have nullsafe versions.
  # flutter_driver:
  #   sdk: flutter
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  # integration_test: ^1.0.1
  test: ^1.16.5
  flutter_launcher_icons: "^0.13.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - audio/
